version: "3.8"
services:
    web:
        build: ./
        ports:
            - "8000:8000"
        links:
            - "database"
        depends_on: 
            - "database"
        env_file:
            - app.env
        command: ["wait-for-it", "database:5432", "--", "bash", "./init-app.sh"]
    database:
        image: "postgres:latest"
        ports: 
            - "5432:5432"
        env_file:
            - app.env  